version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  test-db:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_DATABASE: nest-course